\begin{equation*}
X = \begin{bmatrix}
        \begin{bmatrix} 0 & 0 & 0 & 1 \\ 1 & 0 & 0 & 0 \end{bmatrix} &
        \begin{bmatrix} 0 & 1 & 0 & 0 \\ 1 & 0 & 0 & 1 \end{bmatrix} &
        \begin{bmatrix} 0 & 0 & 1 & 0 \\ 0 & 1 & 0 & 0 \end{bmatrix}
    \end{bmatrix}
\end{equation*}

\begin{align*}
    W_z &= \begin{bmatrix} 0.874 & 1.519 \\ 1.882 & 1.952 \\ -0.527 & 0.565 \\ -0.226 & -0.232 \end{bmatrix} \\
    W_r &= \begin{bmatrix} 0.157 & -0.16 \\ 0.684 & 0.118 \\ 0.128 & 0.318 \\ 0.139 & 0.41 \end{bmatrix} \\
    W_h &= \begin{bmatrix} -1.218 & 1.131 \\ 0.173 & 0.386 \\ -0.837 & -0.298 \\ 0.34 & 0.465 \end{bmatrix} \\
    U_z &= \begin{bmatrix} -0.918 & 0.45 \\ -0.254 & 1.204 \end{bmatrix} \\
    U_r &= \begin{bmatrix} 0.356 & 0.36 \\ 0.235 & 0.023 \end{bmatrix} \\
    U_h &= \begin{bmatrix} 2.142 & 0.485 \\ 1.76 & 0.288 \end{bmatrix} \\
    b_z, b_r, b_h &= \begin{bmatrix} 0 & 0 \\ 0 & 0 \end{bmatrix}
\end{align*}

We wanna compute firts
\begin{align*}
    t &= 0, \quad X_0 = \begin{bmatrix} 0 & 0 & 0 & 1 \\ 1 & 0 & 0 & 0 \end{bmatrix} \\
    X_0 W_z &= \begin{bmatrix}0 & 0 & 0 & 1 \\ 1 & 0 & 0 & 0\end{bmatrix} \times \begin{bmatrix}0.8740 & 1.5188\\ 1.8818 & 1.9524\\ -0.5267 & 0.5650\\ -0.2255 & -0.2316\end{bmatrix} = \begin{bmatrix} -0.2255 & -0.2316 \\ 0.874 & 1.5188 \end{bmatrix}, \quad H_{-1} U_z = \begin{bmatrix} 0 & 0 \\ 0 & 0 \end{bmatrix}, \quad b_z = \begin{bmatrix} 0 & 0 \\ 0 & 0 \end{bmatrix} \\
    Z_0 &= \sigma(X_0 W_z + H_{-1} U_z + b_z) = \begin{bmatrix} 0.4438 & 0.4423 \\ 0.7055 & 0.8203 \end{bmatrix} \\
\end{align*}

\begin{align*}
    X_0 W_r &= \begin{bmatrix} 0.1388 & 0.4100 \\ 0.1567 & -0.1600 \end{bmatrix}, \quad H_{-1} U_r = \begin{bmatrix} 0 & 0 \\ 0 & 0 \end{bmatrix}, \quad b_r = \begin{bmatrix} 0 & 0 \\ 0 & 0 \end{bmatrix} \\
    R_0 &= \sigma(X_0 W_r + H_{-1} U_r + b_r) = \begin{bmatrix} 0.5346 & 0.6010 \\ 0.5390 & 0.4600 \end{bmatrix}
\end{align*}

$t = 0; $
\begin{align}
X_0 = \left[
  \begin{array}{cccc}
  0 & 0 & 0 & 1 \\
  1 & 0 & 0 & 0
  \end{array}
\right]
\end{align}

Update Gate

\begin{align}
    Z_t &= \sigma(X_t W_{z} + H_{t-1} U_{z} + b_z)
\end{align}

\begin{align}
X_0 W_{z} = \left[
  \begin{array}{cccc}
  0 & 0 & 0 & 1 \\
  1 & 0 & 0 & 0
  \end{array}
\right]
\times \left[
  \begin{array}{cccc}
  0.8740 & 1.5188\\
  1.8818 & 1.9524\\
  -0.5267 & 0.5650\\
  -0.2255 & -0.2316
  \end{array}
\right]
=
\left[
  \begin{array}{cccc}
  -0.2255 & -0.2316\\
  0.874 & 1.5188
  \end{array}
\right]
\end{align}

\begin{align}
H_{-1} U_{z} = \left[
  \begin{array}{cccc}
  0 & 0 \\
  0 & 0
  \end{array}
\right]
\times
\left[
  \begin{array}{cccc}
  -0.9176 & 0.4503\\
  -0.2539 & 1.2043
  \end{array}
\right]
=
\left[
  \begin{array}{cccc}
  0 & 0 \\
  0 & 0
  \end{array}
\right]
\end{align}

\begin{align}
b_r = \left[
  \begin{array}{cccc}
  0 & 0 \\
  0 & 0
  \end{array}
\right]
\end{align}

\begin{align}
    Z_0 &= \sigma\left(\left[
  \begin{array}{cccc}
  -0.2255 & -0.2316\\
  0.874 & 1.5188
  \end{array}
\right]+\left[
  \begin{array}{cccc}
  0 & 0 \\
  0 & 0
  \end{array}
\right]+\left[
  \begin{array}{cccc}
  0 & 0 \\
  0 & 0
  \end{array}
\right]\right)
=
\left[
  \begin{array}{cccc}
  0.4438 & 0.4423\\
  0.7055 & 0.8203
  \end{array}
\right]
\end{align}

Reset Gate

\begin{align}
    R_t &= \sigma(X_t W_{r} + H_{t-1} U_{r} + b_r) 
\end{align}


\begin{align}
X_0 W_{r} = \left[
  \begin{array}{cccc}
  0 & 0 & 0 & 1 \\
  1 & 0 & 0 & 0
  \end{array}
\right]
\times \left[
  \begin{array}{cccc}
  0.1567 & -0.1600\\
  0.6844 & 0.1181\\
  0.1278 & 0.3181\\
  0.1388 & 0.4100
  \end{array}
\right]
=
\left[
  \begin{array}{cccc}
  0.1388 & 0.4100\\
  0.1567 & -0.1600
  \end{array}
\right]
\end{align}

\begin{align}
H_{-1} U_{r} = \left[
  \begin{array}{cccc}
  0 & 0 \\
  0 & 0
  \end{array}
\right]
\times \left[
  \begin{array}{cccc}
  0.3557 & 0.3600\\
  0.2347 & 0.0231
  \end{array}
\right]
=
\left[
  \begin{array}{cccc}
  0 & 0 \\
  0 & 0
  \end{array}
\right]
\end{align}

\begin{align}
    R_0 &= \sigma\left(\left[
  \begin{array}{cccc}
  0.1388 & 0.4100\\
  0.1567 & -0.1600
  \end{array}
\right]+\left[
  \begin{array}{cccc}
  0 & 0 \\
  0 & 0
  \end{array}
\right]+\left[
  \begin{array}{cccc}
  0 & 0 \\
  0 & 0
  \end{array}
\right]\right)
=
\left[
  \begin{array}{cccc}
  0.5346 & 0.6010 \\
  0.5390 & 0.4600
  \end{array}
\right]
\end{align}

Candidate For a Hidden State

\begin{align}
\tilde{H}_t &= \tanh(X_t W_{h} + (R_t \odot H_{t-1}) U_{h} + b_h)
\end{align}

\begin{align}
X_0 W_{h} = \left[
  \begin{array}{cccc}
  0 & 0 & 0 & 1 \\
  1 & 0 & 0 & 0
  \end{array}
\right]
\times \left[
  \begin{array}{cccc}
  -1.2179 & 1.1311\\
  0.1728 & 0.3855\\
  -0.8367 & -0.2980\\
  0.3399 & 0.4652
  \end{array}
\right]
=
\left[
  \begin{array}{cccc}
  0.3399 & 0.4652\\
  -1.2179 & 1.1311
  \end{array}
\right]
\end{align}

\begin{align}
(R_t \odot H_{t-1}) U_{h} = 
\left[
  \begin{array}{cccc}
  0 & 0 \\
  0 & 0
  \end{array}
\right]
\end{align}

\begin{align}
\tilde{H}_0 &= \tanh\left(
\left[
  \begin{array}{cccc}
  0.3399 & 0.4652\\
  -1.2179 & 1.1311
  \end{array}
\right] + \left[
  \begin{array}{cccc}
  0 & 0 \\
  0 & 0
  \end{array}
\right] + \left[
  \begin{array}{cccc}
  0 & 0 \\
  0 & 0
  \end{array}
\right]
\right)
=
\left[
  \begin{array}{cccc}
  0.3273 & 0.4343 \\
  -0.8390 & 0.8113
  \end{array}
\right]

\end{align}

Hidden State

\begin{align}
H_t &= (1-Z_t) \odot H_{t-1} + Z_t \odot  \tilde{H}_t 
\end{align}

\begin{align}
(1-Z_0) \odot H_{-1} =
\left(
1 - \left[
  \begin{array}{cccc}
  0.4438 & 0.4423\\
  0.7055 & 0.8203
  \end{array}
\right]
\right)  \odot \left[
  \begin{array}{cccc}
  0 & 0 \\
  0 & 0
  \end{array}
\right] = 
\left[
  \begin{array}{cccc}
  0 & 0 \\
  0 & 0
  \end{array}
\right]

\end{align}

\begin{align}
Z_t \odot \tilde{H}_t =
\left[
  \begin{array}{cccc}
  0.4438 & 0.4423\\
  0.7055 & 0.8203
  \end{array}
\right] \odot
\left[
  \begin{array}{cccc}
  0.3273 & 0.4343 \\
  -0.8390 & 0.8113
  \end{array}
\right] =
\left[
  \begin{array}{cccc}
  0,1452 & 0.1920 \\
  -0.5919 & 0.6655
  \end{array}
\right]

\end{align}


\begin{align}
H_0 &= \left[
  \begin{array}{cccc}
  0,1452 & 0.1920 \\
  -0.5919 & 0.6655
  \end{array}
\right] 
\end{align}

$t = 1; $
\begin{align}
X_1 = \left[
  \begin{array}{cccc}
  0 & 1 & 0 & 0 \\
  1 & 0 & 0 & 1
  \end{array}
\right]
\end{align}

Update Gate

\begin{align}
    Z_t &= \sigma(X_t W_{z} + H_{t-1} U_{z} + b_z)
\end{align}

\begin{align}
X_1 W_{z} = \left[
  \begin{array}{cccc}
  0 & 1 & 0 & 0 \\
  1 & 0 & 0 & 1
  \end{array}
\right]
\times \left[
  \begin{array}{cccc}
  0.8740 & 1.5188\\
  1.8818 & 1.9524\\
  -0.5267 & 0.5650\\
  -0.2255 & -0.2316
  \end{array}
\right]
=
\left[
  \begin{array}{cccc}
  1.8818 & 1.9524\\
  0.6485 & 1.2872
  \end{array}
\right]
\end{align}

\begin{align}
H_0 U_{z} = \left[
  \begin{array}{cccc}
  0,1452 & 0.1920 \\
  -0.5919 & 0.6655
  \end{array}
\right] 
\times
\left[
  \begin{array}{cccc}
  -0.9176 & 0.4503\\
  -0.2539 & 1.2043
  \end{array}
\right]
=
\left[
  \begin{array}{cccc}
  -0.1819 & 0.2966 \\
  -0.3741 & 0.5349
  \end{array}
\right]
\end{align}

\begin{align}
    Z_1 &= \sigma\left(\left[
  \begin{array}{cccc}
  1.8818 & 1.9524\\
  0.6485 & 1.2872
  \end{array}
\right]+\left[
  \begin{array}{cccc}
  -0.1819 & 0.2966 \\
  -0.3741 & 0.5349
  \end{array}
\right]+\left[
  \begin{array}{cccc}
  0 & 0 \\
  0 & 0
  \end{array}
\right]\right)
=
\sigma\left(\left[
  \begin{array}{cccc}
  1.6999 & 2.249\\
  0.2744 & 1.8221
  \end{array}
\right]\right) 
=
\left[
\begin{array}{cccc}
  0.4430 & 0.4694\\
  0.5351 & 0.7156
\end{array}
\right]
\end{align}

Reset Gate

\begin{align}
    R_t &= \sigma(X_t W_{r} + H_{t-1} U_{r} + b_r) 
\end{align}


\begin{align}
X_1 W_{r} = \left[
  \begin{array}{cccc}
  0 & 1 & 0 & 0 \\
  1 & 0 & 0 & 1
  \end{array}
\right]
\times \left[
  \begin{array}{cccc}
  -1.2181 & -0.8113\\
  0.6912 & -1.8349\\
  1.2232 & -0.0376\\
  0.7532 & -0.4603
  \end{array}
\right]
=
\left[
  \begin{array}{cccc}
  0.6912 & -1.8349\\
  -0.4649 & -1.2716
  \end{array}
\right]
\end{align}

\begin{align}
H_{0} U_{r} = 
\left[
  \begin{array}{cccc}
  0,1452 & 0.1920 \\
  -0.5919 & 0.6655
  \end{array}
\right] 
\times
\left[
  \begin{array}{cccc}
  0.8122 & 0.5938\\
  -1.9665 & -0.3766
  \end{array}
\right]
=
\left[
  \begin{array}{cccc}
  -0.2596 & 0.0139 \\
  -1.7894 & -0.6020
  \end{array}
\right]
\end{align}

\begin{align}
    R_1 = \sigma\left(\left[
  \begin{array}{cccc}
  0.6912 & -1.8349\\
  -0.4649 & -1.2716
  \end{array}
\right]+\left[
  \begin{array}{cccc}
  -0.2596 & 0.0139 \\
  -1.7894 & -0.6020
  \end{array}
\right]+\left[
  \begin{array}{cccc}
  0 & 0 \\
  0 & 0
  \end{array}
\right]\right)
=
\sigma\left(\left[
  \begin{array}{cccc}
  0.4316 & -1.8210 \\
  -2.2543 & -1.8736
  \end{array}
\right]\right)
=
\left[
  \begin{array}{cccc}
  0.6062 & 0.1393 \\
  0.0949 & 0.1331
  \end{array}
\right]
\end{align}

Candidate For a Hidden State

\begin{align}
\tilde{H}_t &= \tanh(X_t W_{h} + (R_t \odot H_{t-1}) U_{h} + b_h)
\end{align}

\begin{align}
X_1 W_{h} = \left[
  \begin{array}{cccc}
  0 & 1 & 0 & 0 \\
  1 & 0 & 0 & 1
  \end{array}
\right]
\times \left[
  \begin{array}{cccc}
  0.7263 & 1.0992\\
  0.1728 & 0.1083\\
  0.5077 & -0.6043\\
 -0.0136 & 1.7521
  \end{array}
\right]
=
\left[
  \begin{array}{cccc}
  0.1728 & 0.1083\\
  0.7127 & 2.8513
  \end{array}
\right]
\end{align}

\begin{align}
(R_1 \odot H_0) U_{h} = 
\left(
  \left[
  \begin{array}{cccc}
  0.6062 & 0.1393 \\
  0.0949 & 0.1331
  \end{array}
\right]
\odot
\left[
  \begin{array}{cccc}
  0,1452 & 0.1920 \\
  -0.5919 & 0.6655
  \end{array}
\right] 
\right)
\times
\left[
  \begin{array}{cccc}
  -0.0504 & 0.6106 \\
  0.7263 & 0.0643
  \end{array}
\right] 
=
\left[
  \begin{array}{cccc}
  0.0149 & 0.0554 \\
  0.0671 & -0.0286
  \end{array}
\right]
\end{align}

\begin{align}
b_h = 
\left[
  \begin{array}{cccc}
  0 & 0 \\
  0 & 0
  \end{array}
\right]

\end{align}

\begin{align}
\tilde{H}_1 &= \tanh\left(
\left[
  \begin{array}{cccc}
  0.1728 & 0.1083\\
  0.7127 & 2.8513
  \end{array}
\right] + \left[
  \begin{array}{cccc}
  0.0149 & 0.0554 \\
  0.0671 & -0.0286
  \end{array}
\right] + \left[
  \begin{array}{cccc}
  0 & 0 \\
  0 & 0
  \end{array}
\right]
\right)
=
\tanh\left(
\left[
  \begin{array}{cccc}
  0.1877 & 0.1637 \\
  0.7798 & 2.8227
  \end{array}
\right]
\right)
=
\left[
  \begin{array}{cccc}
  0.1855 & 0.1622 \\
  0.6525 & 0.9929
  \end{array}
\right]

\end{align}

Hidden State

\begin{align}
H_t &= (1-Z_t) \odot H_{t-1} + Z_t \odot  \tilde{H}_t 
\end{align}

\begin{align}
(1-Z_1) \odot H_0 =
\left(
1 - \left[
\begin{array}{cccc}
  0.4430 & 0.4694\\
  0.5351 & 0.7156
\end{array}
\right]
\right)  \odot \left[
  \begin{array}{cccc}
  0,1452 & 0.1920 \\
  -0.5919 & 0.6655
  \end{array}
\right]  = 
\left[
  \begin{array}{cccc}
  0 & 0 \\
  0 & 0
  \end{array}
\right]

\end{align}

\begin{align}
Z_1 \odot \tilde{H}_1 =
\left[
  \begin{array}{cccc}
  0.4438 & 0.4423\\
  0.7055 & 0.8203
  \end{array}
\right] \odot
\left[
  \begin{array}{cccc}
  0.3273 & 0.4343 \\
  -0.8390 & 0.8113
  \end{array}
\right] =
\left[
  \begin{array}{cccc}
  0,1452 & 0.1920 \\
  -0.5919 & 0.6655
  \end{array}
\right]

\end{align}


\begin{align}
H_0 &= \left[
  \begin{array}{cccc}
  0,1452 & 0.1920 \\
  -0.5919 & 0.6655
  \end{array}
\right] 
\end{align}

In [27]:
import torch
import plotly.graph_objs as go
from ipywidgets import interact, IntSlider
from IPython.display import display

In [28]:
import numpy as np

# Specify the dimensions of the weight matrix
num_rows = 2
num_cols = 2

# Mean and standard deviation for the normal distribution
mean = 0.0
std_dev = 1.0

# Create a weight matrix with normally distributed values
weight_matrix = np.random.normal(mean, std_dev, size=(num_rows, num_cols))

print("Weight Matrix:")
print(weight_matrix)


Weight Matrix:
[[-0.11701692 -1.81718436]
 [ 0.72764897 -1.55450602]]


In [29]:
import torch
import torch.nn as nn
from torch.autograd import Variable
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence
import torch.nn.functional as F
import numpy as np
import itertools
import pickle

%autosave 180

Autosaving every 180 seconds


In [30]:
X = torch.tensor(
    [
        [
            [[0., 0., 0., 1.], [1., 0., 0., 0.]],
            [[0., 1., 0., 0.], [0., 0., 0., 1.]],
            [[0., 0., 1., 0.], [0., 1., 0., 0.]],
        ],
        [
            [[0., 0., 1., 0.], [0., 1., 0., 0.]],
            [[1., 0., 0., 0.], [0., 0., 1., 0.]],
            [[0., 0., 0., 1.], [1., 0., 0., 0.]],
        ],
        [
            [[0., 0., 0., 1.], [1., 0., 0., 0.]],
            [[0., 1., 0., 0.], [0., 0., 0., 1.]],
            [[0., 0., 1., 0.], [0., 1., 0., 0.]],
        ],
    ],
    dtype=torch.float32,
)

batch_size = 2
seq_length = 3
num_samples = 3
vocab_size = 4

torch.manual_seed(1) # reproducibility

####  Define the network parameters:
hiddenSize = 2 # network size, this can be any number (depending on your task)
numClass = 4 # this is the same as our vocab_size

#### Weight matrices for our inputs 
Wz = Variable(torch.randn(vocab_size, hiddenSize), requires_grad=True)
Wr = Variable(torch.randn(vocab_size, hiddenSize), requires_grad=True)
Wh = Variable(torch.randn(vocab_size, hiddenSize), requires_grad=True)

## Intialize the hidden state
# this is for demonstration purposes only, in the actual model it will be initiated during training a loop over the 
# the number of bacthes and updated before passing to the next GRU cell.
h_t_demo = torch.zeros(batch_size, hiddenSize) 

#### Weight matrices for our hidden layer
Uz = Variable(torch.randn(hiddenSize, hiddenSize), requires_grad=True)
Ur = Variable(torch.randn(hiddenSize, hiddenSize), requires_grad=True)
Uh = Variable(torch.randn(hiddenSize, hiddenSize), requires_grad=True)

#### bias vectors for our hidden layer
bz = Variable(torch.zeros(hiddenSize), requires_grad=True)
br = Variable(torch.zeros(hiddenSize), requires_grad=True)
bh = Variable(torch.zeros(hiddenSize), requires_grad=True)

#### Output weights
Wy = Variable(torch.randn(hiddenSize, numClass), requires_grad=True)
by = Variable(torch.zeros(numClass), requires_grad=True)

h_t_1 = []
h = h_t_demo
for i,sequence in enumerate(X[0]):
    z = torch.sigmoid(torch.matmul(sequence, Wz) + torch.matmul(h, Uz) + bz)
    r = torch.sigmoid(torch.matmul(sequence, Wr) + torch.matmul(h, Ur) + br)
    h_tilde = torch.tanh(torch.matmul(sequence, Wh) + torch.matmul(r * h, Uh) + bh)
    h = z * h + (1 - z) * h_tilde
    h_t_1.append(h)
    print(f'h{i}:{h}')
h_t_1 = torch.stack(h_t_1)

In [31]:
batch_size = 2
seq_length = 3
num_samples = 3
vocab_size = 4

In [39]:
torch.manual_seed(1) # reproducibility

####  Define the network parameters:
hiddenSize = 2 # network size, this can be any number (depending on your task)
numClass = 4 # this is the same as our vocab_size

#### Weight matrices for our inputs 
Wz = Variable(torch.randn(vocab_size, hiddenSize), requires_grad=True)
Wr = Variable(torch.randn(vocab_size, hiddenSize), requires_grad=True)
Wh = Variable(torch.randn(vocab_size, hiddenSize), requires_grad=True)

## Intialize the hidden state
# this is for demonstration purposes only, in the actual model it will be initiated during training a loop over the 
# the number of bacthes and updated before passing to the next GRU cell.
h_t_demo = torch.zeros(batch_size, hiddenSize) 

#### Weight matrices for our hidden layer
Uz = Variable(torch.randn(hiddenSize, hiddenSize), requires_grad=True)
Ur = Variable(torch.randn(hiddenSize, hiddenSize), requires_grad=True)
Uh = Variable(torch.randn(hiddenSize, hiddenSize), requires_grad=True)

#### bias vectors for our hidden layer
bz = Variable(torch.zeros(hiddenSize), requires_grad=True)
br = Variable(torch.zeros(hiddenSize), requires_grad=True)
bh = Variable(torch.zeros(hiddenSize), requires_grad=True)

#### Output weights
Wy = Variable(torch.randn(hiddenSize, numClass), requires_grad=True)
by = Variable(torch.zeros(numClass), requires_grad=True)

In [33]:
Wz, Wr, Wh, Uz, Ur, Uh, bz, br, bh, Wy, by

(tensor([[ 0.6614,  0.2669],
         [ 0.0617,  0.6213],
         [-0.4519, -0.1661],
         [-1.5228,  0.3817]], requires_grad=True),
 tensor([[-1.0276, -0.5631],
         [-0.8923, -0.0583],
         [-0.1955, -0.9656],
         [ 0.4224,  0.2673]], requires_grad=True),
 tensor([[-0.4212, -0.5107],
         [-1.5727, -0.1232],
         [ 3.5870, -1.8313],
         [ 1.5987, -1.2770]], requires_grad=True),
 tensor([[ 0.3255, -0.4791],
         [ 1.3790,  2.5286]], requires_grad=True),
 tensor([[ 0.4107, -0.9880],
         [-0.9081,  0.5423]], requires_grad=True),
 tensor([[ 0.1103, -2.2590],
         [ 0.6067, -0.1383]], requires_grad=True),
 tensor([0., 0.], requires_grad=True),
 tensor([0., 0.], requires_grad=True),
 tensor([0., 0.], requires_grad=True),
 tensor([[ 0.8310, -0.2477, -0.8029,  0.2366],
         [ 0.2857,  0.6898, -0.6331,  0.8795]], requires_grad=True),
 tensor([0., 0., 0., 0.], requires_grad=True))

In [34]:
h_t_1 = []
h = h_t_demo
for i,sequence in enumerate(X[0]):
    z = torch.sigmoid(torch.matmul(sequence, Wz) + torch.matmul(h, Uz) + bz)
    r = torch.sigmoid(torch.matmul(sequence, Wr) + torch.matmul(h, Ur) + br)
    h_tilde = torch.tanh(torch.matmul(sequence, Wh) + torch.matmul(r * h, Uh) + bh)
    h = z * h + (1 - z) * h_tilde
    h_t_1.append(h)
    print(f'h{i}:{h}')
h_t_1 = torch.stack(h_t_1)

h0:tensor([[ 0.7565, -0.3472],
        [-0.1355, -0.2040]], grad_fn=<AddBackward0>)
h1:tensor([[-0.1535, -0.5712],
        [ 0.7664, -0.5062]], grad_fn=<AddBackward0>)
h2:tensor([[ 0.7495, -0.8616],
        [-0.2399, -0.6680]], grad_fn=<AddBackward0>)


In [40]:
import torch
import ipywidgets as widgets
from IPython.display import display

# Your code for calculating hidden states
def compute_hidden_states(X, Wz, Uz, bz, Wr, Ur, br, Wh, Uh, bh, h_t_demo):
    h_t_1 = []
    h = h_t_demo
    for i, sequence in enumerate(X):
        z = torch.sigmoid(torch.matmul(sequence, Wz) + torch.matmul(h, Uz) + bz)
        r = torch.sigmoid(torch.matmul(sequence, Wr) + torch.matmul(h, Ur) + br)
        h_tilde = torch.tanh(torch.matmul(sequence, Wh) + torch.matmul(r * h, Uh) + bh)
        h = z * h + (1 - z) * h_tilde
        h_t_1.append(h)
        print(f'h{i}:{h}')
    return torch.stack(h_t_1)

# Interactive Widget
batch_size = X.shape[1]
hidden_size = h_t_demo.shape[1]

sequence_slider = widgets.IntSlider(min=0, max=X.shape[0]-1, step=1, value=0, description='Sequence Index')
compute_button = widgets.Button(description='Compute Hidden States')
output_text = widgets.Output()

def compute_hidden_states_handler(b):
    with output_text:
        output_text.clear_output()
        sequence_index = sequence_slider.value
        sequence = X[sequence_index].view(batch_size, vocab_size)
        result = compute_hidden_states(sequence, Wz, Uz, bz, Wr, Ur, br, Wh, Uh, bh, h_t_demo)
        print(f"Hidden States for Sequence {sequence_index}:\n{result}")

compute_button.on_click(compute_hidden_states_handler)

display(sequence_slider)
display(compute_button)
display(output_text)


IntSlider(value=0, description='Sequence Index', max=2)

Button(description='Compute Hidden States', style=ButtonStyle())

Output()

In [78]:
import torch
import ipywidgets as widgets
from IPython.display import display
import matplotlib.pyplot as plt
import seaborn as sns

vocab_size = 4
hiddenSize = 2
numClass = 4
batch_size = 1

def initialize_input_tensor():
    X = torch.tensor(
        [
            [
                [[0., 0., 0., 1.], [1., 0., 0., 0.]],
                [[0., 1., 0., 0.], [0., 0., 0., 1.]],
                [[0., 0., 1., 0.], [0., 1., 0., 0.]],
            ],
            [
                [[0., 0., 1., 0.], [0., 1., 0., 0.]],
                [[1., 0., 0., 0.], [0., 0., 1., 0.]],
                [[0., 0., 0., 1.], [1., 0., 0., 0.]],
            ],
            [
                [[0., 1., 0., 0.], [0., 1., 0., 0.]],
                [[0., 1., 0., 0.], [1., 0., 0., 0.]],
                [[1., 0., 0., 0.], [0., 0., 0., 1.]],
            ],
        ],
        dtype=torch.float32,
    )
    
    return X

def initialize_weight_params(vocab_size, hiddenSize, numClass, batch_size):
    torch.manual_seed(1) # reproducibility

    #### Weight matrices for our inputs 
    Wz = torch.randn(vocab_size, hiddenSize, requires_grad=True)
    Wr = torch.randn(vocab_size, hiddenSize, requires_grad=True)
    Wh = torch.randn(vocab_size, hiddenSize, requires_grad=True)

    h_t_demo = torch.zeros(batch_size, hiddenSize) 

    #### Weight matrices for our hidden layer
    Uz = torch.randn(hiddenSize, hiddenSize, requires_grad=True)
    Ur = torch.randn(hiddenSize, hiddenSize, requires_grad=True)
    Uh = torch.randn(hiddenSize, hiddenSize, requires_grad=True)

    #### bias vectors for our hidden layer
    bz = torch.zeros(hiddenSize, requires_grad=True)
    br = torch.zeros(hiddenSize, requires_grad=True)
    bh = torch.zeros(hiddenSize, requires_grad=True)

    #### Output weights
    Wy = torch.randn(hiddenSize, numClass, requires_grad=True)
    by = torch.zeros(numClass, requires_grad=True)
    
    return Wz, Wr, Wh, h_t_demo, Uz, Ur, Uh, bz, br, bh, Wy, by

def compute_hidden_states(sequence, Wz, Wr, Wh, Uz, Ur, Uh, bz, br, bh, h_t_demo):
    h_t_1 = []
    h = h_t_demo
    for i,sequence in enumerate(sequence):   # iterate over each sequence in the batch to calculate the hidden state h 
        z = torch.sigmoid(torch.matmul(sequence, Wz) + torch.matmul(h, Uz) + bz)
        r = torch.sigmoid(torch.matmul(sequence, Wr) + torch.matmul(h, Ur) + br)
        h_tilde = torch.tanh(torch.matmul(sequence, Wh) + torch.matmul(r * h, Uh) + bh)
        h = z * h + (1 - z) * h_tilde
        h_t_1.append(h)
        print(f'h{i}:{h.tolist()}')
    h_t_1 = torch.stack(h_t_1)
    return h_t_1

Wz, Wr, Wh, h_t_demo, Uz, Ur, Uh, bz, br, bh, Wy, by = initialize_weight_params(vocab_size, hiddenSize, numClass, batch_size)
X = initialize_input_tensor()
compute_hidden_states(X[0], Wz, Wr, Wh, Uz, Ur, Uh, bz, br, bh, h_t_demo)
compute_hidden_states(X[1], Wz, Wr, Wh, Uz, Ur, Uh, bz, br, bh, h_t_demo)
compute_hidden_states(X[2], Wz, Wr, Wh, Uz, Ur, Uh, bz, br, bh, h_t_demo)

h0:[[0.7564791440963745, -0.3471693992614746], [-0.13547198474407196, -0.2040339857339859]]
h1:[[-0.15354949235916138, -0.5712474584579468], [0.7663647532463074, -0.5062339305877686]]
h2:[[0.7494825720787048, -0.8616112470626831], [-0.2398536205291748, -0.6680415868759155]]
h0:[[0.6101565361022949, -0.5143395662307739], [-0.44458237290382385, -0.04285608232021332]]
h1:[[0.13207115232944489, -0.7347888946533203], [0.5053126811981201, -0.4782966077327728]]
h2:[[0.8309597373008728, -0.8687419891357422], [0.07650101184844971, -0.681564211845398]]
h0:[[-0.44458237290382385, -0.04285608232021332], [-0.44458237290382385, -0.04285608232021332]]
h1:[[-0.700114369392395, 0.01752728782594204], [-0.4341435432434082, -0.13308364152908325]]
h2:[[-0.5863999128341675, -0.050202928483486176], [0.7255433797836304, -0.3351801633834839]]


tensor([[[-0.4446, -0.0429],
         [-0.4446, -0.0429]],

        [[-0.7001,  0.0175],
         [-0.4341, -0.1331]],

        [[-0.5864, -0.0502],
         [ 0.7255, -0.3352]]], grad_fn=<StackBackward0>)

In [81]:
def update_hidden_states(sequence_index):
    with output_text:
        output_text.clear_output()
        sequence = X[sequence_index]
        hidden_states = compute_hidden_states(sequence, Wz, Wr, Wh, Uz, Ur, Uh, bz, br, bh, h_t_demo)

widgets.interactive(update_hidden_states, sequence_index=sequence_slider)

display(sequence_slider)
display(output_text)

IntSlider(value=0, description='Sequence Index', max=2)

Output(outputs=({'name': 'stdout', 'text': 'h0:[[0.7564791440963745, -0.3471693992614746], [-0.135471984744071…

In [96]:
sequence_input = widgets.IntSlider(min=0, max=2, step=1, value=0, description='Sequence Index')
output_text = widgets.Output()

def update_hidden_states(sequence_index):
    with output_text:
        output_text.clear_output()
        sequence = X[sequence_index]
        hidden_states = compute_hidden_states(sequence, Wz, Wr, Wh, Uz, Ur, Uh, bz, br, bh, h_t_demo)
# Use sequence_input instead of sequence_slider
widgets.interactive(update_hidden_states, sequence_index=sequence_input)

# Use sequence_input instead of sequence_slider
display(sequence_input)
display(output_text)

IntSlider(value=0, description='Sequence Index', max=2)

Output()